### ISSUE TITLE
How to start a service of windows driver

### ISSUE THREAD

**Issue by Haagaau22** [belvedere-trading/pywinservicemanager#1]
hi
i try you module,maybe it only support python2.
in fact, i write a simple driver by C, and i want to use pywin32 to install and start it.But i get some error when i start it.
The detail is [here](http://stackoverflow.com/questions/37051319/startservice-to-start-a-windows-driver).
Would you help me ?

**Comment by DennisHarper** [comment]
Hi @Zonzely,
The error that you mentioned in the other post seems to be coming from the Operating System loading the binary and nothing to do with the Service Manager:
pywintypes.error: (129,'StartService', 'The %1 application cannot run in Win32 mode.')

One thing that I saw online that you can try is starting the service with an administrator account. Also, once the service is installed, you can use the 'Component Services' gui to manipulate the configurations of the service and test starting the service without any other dependencies.

Good Luck!
