### ISSUE TITLE
Failed to Start Flask service. The service did not respond to the start or control request in a timely fashion

### ISSUE THREAD

**Issue by sayantan94** [belvedere-trading/pywinservicemanager#12]
**Create NewService.py file**
```
from pywinservicemanager.WindowsServiceConfigurationManager import CreateService
from pywinservicemanager.NewServiceDefinition import NewServiceDefinition

serviceName = 'FlaskAppService'
displayName = 'MyFlaskApp'
binaryPathName = 'C:\\Users\\python.exe c:\\FlaskApp\\Hello.py'
    
newServiceDefinition = NewServiceDefinition(serviceName=serviceName,
                                           displayName=displayName,
                                           binaryPathName=binaryPathName)

flaskService= CreateService(newServiceDefinition)

# Successfully adds the service with windows service manager.
flaskService.Save()
# Error occurs while staring the registered service
flaskService.Start()`
```

**c:\\FlaskApp\\Hello.py File:**
```
from flask import Flask
app = Flask(__name__)
from flask import request

def shutdown_server():
    func = request.environ.get('werkzeug.server.shutdown')
    if func is None:
        raise RuntimeError('Not running with the Werkzeug Server')
    func()

@app.route("/")
def hello():
    return "Hello World!"

@app.route('/shutdown', methods=['POST'])
def shutdown():
    shutdown_server()
    return 'Server shutting down...'

if __name__ == "__main__":
    app.run()
```
While executing NewService.py file, it does registers the service with windows service manager but fails to start the service throwing an exception as 

> Error 1053: The service did not respond to the start or control request in a timely fashion

Is this the correct way to implement creating and starting of a FlaskService ?

**Comment by DennisHarper** [comment]
Hello sayantan94,

PyWinServiceManager only implements calls to the Windows service control API functions You still need to create the "Windows Service". To create a proper windows service in python, you need to implement  an entry point that inherits from the win32serviceutil.ServiceFramework module located in the pywin32 python package (Many examples online on how to do so).

Hope this helps!
